# Generated by Django 6.0.3 on 2026-03-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_doctor_consultation_fee_doctor_specialization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_medication",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
