# Generated by Django 6.0.3 on 2026-04-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_patient_allergies_patient_current_medication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="patient",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="contact",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
