# Generated by Django 6.0.3 on 2026-04-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_patient_blood_group_patient_emergency_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
