# Generated by Django 6.0.3 on 2026-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_patient_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="lab_reports",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
