# Generated by Django 6.0.3 on 2026-04-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_patient_lab_reports"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="lab_reports",
        ),
    ]
