# Generated by Django 6.0.3 on 2026-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_patient_lab_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="insurance_info",
            field=models.TextField(blank=True),
        ),
    ]
