# Generated by Django 6.0.3 on 2026-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_patient_insurance_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
