# Generated by Django 6.0.3 on 2026-05-04 18:12

from django.db import migrations, models


def populate_doctor_codes(apps, schema_editor):
    """Assign unique doctor codes to existing doctors before unique constraint is applied."""
    Doctor = apps.get_model('users', 'Doctor')
    User = apps.get_model('users', 'User')
    used_codes = set()

    for doctor in Doctor.objects.select_related('user').all():
        name = doctor.user.first_name or doctor.user.username
        # Remove Dr. prefix
        name = name.replace('Dr.', '').replace('Dr ', '').strip()
        base = ''.join(c for c in name if c.isalpha())[:3].upper() or 'DOC'

        candidate = base
        counter = 1
        while candidate in used_codes:
            candidate = f"{base}{counter}"
            counter += 1

        doctor.doctor_code = candidate
        doctor.save(update_fields=['doctor_code'])
        used_codes.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_email"),
    ]

    operations = [
        # Step 1: Add the field WITHOUT unique constraint, allowing blank
        migrations.AddField(
            model_name="doctor",
            name="doctor_code",
            field=models.CharField(
                blank=True,
                default='',
                help_text="Short unique code used in composite tokens (e.g. VIR, KIR)",
                max_length=5,
            ),
        ),
        # Step 2: Populate codes for all existing doctors
        migrations.RunPython(populate_doctor_codes, migrations.RunPython.noop),
        # Step 3: Now apply the unique constraint
        migrations.AlterField(
            model_name="doctor",
            name="doctor_code",
            field=models.CharField(
                blank=True,
                help_text="Short unique code used in composite tokens (e.g. VIR, KIR)",
                max_length=5,
                unique=True,
            ),
        ),
    ]
