# Generated by Django 6.0.3 on 2026-03-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("token_number", models.PositiveIntegerField()),
                (
                    "estimated_wait_time",
                    models.PositiveIntegerField(
                        help_text="Estimated wait time in minutes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No-Show"),
                        ],
                        default="BOOKED",
                        max_length=20,
                    ),
                ),
                ("doctor_remark", models.TextField(blank=True, null=True)),
                ("prescription", models.TextField(blank=True, null=True)),
                ("advice", models.TextField(blank=True, null=True)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date", "token_number"],
            },
        ),
    ]
