# Generated by Django 6.0.3 on 2026-03-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("FOLLOWUP", "Follow-Up")],
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reason",
            field=models.TextField(blank=True, help_text="Reason for visit"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No-Show"),
                ],
                db_index=True,
                default="BOOKED",
                max_length=20,
            ),
        ),
    ]
