# Generated by Django 6.0.3 on 2026-03-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appointments",
            "0003_appointment_appointment_type_appointment_reason_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("ARRIVED", "Arrived"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No-Show"),
                ],
                db_index=True,
                default="BOOKED",
                max_length=20,
            ),
        ),
    ]
