# Generated by Django 6.0.3 on 2026-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="bp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="heart_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="prescription",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
