# Generated by Django 6.0.3 on 2026-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_labreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("ARRIVED", "Arrived"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("NO_SHOW", "No-Show"),
                ],
                db_index=True,
                default="BOOKED",
                max_length=20,
            ),
        ),
    ]
